volumes:
  moodmo_dev_postgres_data: {}
  moodmo_dev_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: moodmo_dev_django
    container_name: moodmo_dev_django
    depends_on:
      - postgres
      - mailpit
      - memcached
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: moodmo_dev_postgres
    volumes:
      - moodmo_dev_postgres_data:/var/lib/postgresql/data
      - moodmo_dev_postgres_data_backups:/backups
    env_file:
      - ./.env

  memcached:
    image: memcached:1.6.26-alpine3.19
    container_name: moodmo_dev_memcached
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: moodmo_dev_mailpit
    ports:
      - "8025:8025"
