version: "3.8"

volumes:
  moodmo_dev_postgres_data: {}
  moodmo_dev_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: moodmo_dev_django
    container_name: moodmo_dev_django
    depends_on:
      - postgres
      - mailpit
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: moodmo_dev_postgres
    volumes:
      - moodmo_dev_postgres_data:/var/lib/postgresql/data
      - moodmo_dev_postgres_data_backups:/backups
    env_file:
      - ./.env

  redis:
    image: "redis:7.2.4-alpine3.19"
    container_name: moodmo_dev_redis
    env_file:
      - ./.env
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit:v1.13.1
    container_name: moodmo_dev_mailpit
    ports:
      - "8025:8025"
