# Generated by Django 4.2.7 on 2023-11-20 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_mood_last_modified_alter_mood_mood_alter_mood_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
