# Generated by Django 4.2.8 on 2023-12-22 10:04

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_alter_mood_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
