# Generated by Django 4.2.8 on 2023-12-22 11:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0005_mood_search_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mood',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='moods_mood_search__f63864_gin'),
        ),
    ]
