# Generated by Django 4.2.9 on 2024-01-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0007_activity_mood_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
    ]
