# Generated by Django 4.2.9 on 2024-01-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('moods', '0008_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='activities',
            field=models.ManyToManyField(blank=True, to='activities.activity'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
