# Generated by Django 4.2.11 on 2024-04-04 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0008_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='mood',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='activity',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mood',
            name='activities',
            field=models.ManyToManyField(blank=True, to='moods.activity'),
        ),
    ]
