# Generated by Django 5.0.4 on 2024-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0009_alter_mood_options_remove_mood_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.SmallIntegerField(choices=[(-2, 'very unhappy'), (-1, 'unhappy'), (0, 'neutral'), (1, 'happy'), (2, 'very happy')]),
        ),
    ]
