# Generated by Django 4.2.11 on 2024-03-20 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0009_alter_mood_activities_delete_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
