from django.urls import path
from .views import (
    MoodListView,
    MoodInfiniteListView,
    MoodSearchView,
    MoodCreateView,
    MoodUpdateView,
    MoodDeleteView,
    MoodImportView,
    MoodExportView,
)

urlpatterns = [
    path(
        "",
        MoodListView.as_view(),
        name="mood_list",
    ),
    path(
        "infinite/",
        MoodInfiniteListView.as_view(),
        name="mood_list_infinite",
    ),
    path(
        "search/",
        MoodSearchView.as_view(),
        name="mood_search",
    ),
    path(
        "create/",
        MoodCreateView.as_view(),
        name="mood_create",
    ),
    path(
        "edit/<int:pk>",
        MoodUpdateView.as_view(),
        name="mood_edit",
    ),
    path(
        "delete/<int:pk>",
        MoodDeleteView.as_view(),
        name="mood_delete",
    ),
    path(
        "export/",
        MoodExportView.as_view(),
        name="mood_export",
    ),
    path(
        "import/",
        MoodImportView.as_view(),
        name="mood_import",
    ),
]
